<?php
$kecamatan = [
    'Adiwerna',
    'Balapulang',
    'Bojong',
    'Bumijawa',
    'Dukuhturi',
    'Dukuhwaru',
    'Jatinegara',
    'Kedungbanteng',
    'Kramat',
    'Lebaksiu',
    'Margasari',
    'Pagerbarang',
    'Pangkah',
    'Slawi',
    'Suradadi',
    'Talang',
    'Tarub',
    'Warureja'
];
?> 